Refactor Home related classes
dedis/student_21_pop pull request #211
Opened 2021-02-10 19:33 UTC by celinecamacho

Implement one ViewModel class to handle Home, Launch and Connect related fragments.

2021-02-11 10:08 UTC, gnarula requested changes
Have a few suggestions on invoking the viewModel methods instead of simulating the click.

I think the call to `(HomeActivity) getActivity().setupZZZButton` is safe as long as we're certain that getActivity() returns a HomeActivity. While this holds true for now, I'm not sure if it would for say the `CameraPermissionFragment` which is inflated from multiple activities.

I reckon the `CameraPermissionFragment` should be refactored to have a `CameraPermissionViewModel` which is an interface that `HomeViewModel` and `LAODetailViewModel` (not sure about the naming yet) can implement.

```java
public interface CameraPermissionViewModel {
    void onPermissionGranted();

    void onPermissionDenied();
}
```

`CameraPermissionFragment` can then look like:

```java
public class CameraPermissionFragment extends Fragment {
    // ..

    private CameraPermissionViewModel mCameraPermissionViewModel;

    @Nullable
  @Override
  public View onCreateView(
          @NonNull LayoutInflater inflater,
          @Nullable ViewGroup container,
          @Nullable Bundle savedInstanceState) {

    mLaunchFragBinding = FragmentLaunchBinding.inflate(inflater, container, false);

    Activity activity = getActivity();
    if (activity instanceof HomeActivity) {
        mCameraPermissionViewModel = HomeActivity.obtainViewModel(activity);
    } else if (activity instanceof  LAODetailActivity) {
        mCameraPermissionViewModel = LAODetailActivity.obtainViewModel(activity);
    } else {
        throw new Exception("cannot obtain view model");
    }

    mLaunchFragBinding.setViewmodel(mHomeViewModel);
    mLaunchFragBinding.setLifecycleOwner(getActivity());

    return mLaunchFragBinding.getRoot();
  }

  // ..
}
```

I'm thinking about a similar pattern for `QRCodeScanningFragment`. Perhaps the calls to `setupZZZButton` can be abstracted away in an interface as well. What do you think?

2021-02-11 14:09 UTC, celinecamacho commented on app/src/main/java/com/github/dedis/student20_pop/ui/LaunchFragment.java
> +  public static HomeViewModel obtainViewModel(Fragment fragment) {
Indeed

2021-02-11 14:50 UTC, celinecamacho commented
> Have a few suggestions on invoking the viewModel methods instead of simulating the click.
> 
> I think the call to `(HomeActivity) getActivity().setupZZZButton` is safe as long as we're certain that getActivity() returns a HomeActivity. While this holds true for now, I'm not sure if it would for say the `CameraPermissionFragment` which is inflated from multiple activities.
> 
> I reckon the `CameraPermissionFragment` should be refactored to have a `CameraPermissionViewModel` which is an interface that `HomeViewModel` and `LAODetailViewModel` (not sure about the naming yet) can implement.
> 
> ```java
> public interface CameraPermissionViewModel {
>     void onPermissionGranted();
> 
>     void onPermissionDenied();
> }
> ```
> 
> `CameraPermissionFragment` can then look like:
> 
> ```java
> public class CameraPermissionFragment extends Fragment {
>     // ..
> 
>     private CameraPermissionViewModel mCameraPermissionViewModel;
> 
>     @Nullable
>   @Override
>   public View onCreateView(
>           @NonNull LayoutInflater inflater,
>           @Nullable ViewGroup container,
>           @Nullable Bundle savedInstanceState) {
> 
>     mLaunchFragBinding = FragmentLaunchBinding.inflate(inflater, container, false);
> 
>     Activity activity = getActivity();
>     if (activity instanceof HomeActivity) {
>         mCameraPermissionViewModel = HomeActivity.obtainViewModel(activity);
>     } else if (activity instanceof  LAODetailActivity) {
>         mCameraPermissionViewModel = LAODetailActivity.obtainViewModel(activity);
>     } else {
>         throw new Exception("cannot obtain view model");
>     }
> 
>     mLaunchFragBinding.setViewmodel(mHomeViewModel);
>     mLaunchFragBinding.setLifecycleOwner(getActivity());
> 
>     return mLaunchFragBinding.getRoot();
>   }
> 
>   // ..
> }
> ```
> 
> I'm thinking about a similar pattern for `QRCodeScanningFragment`. Perhaps the calls to `setupZZZButton` can be abstracted away in an interface as well. What do you think?

If I understand correctly, there would be two interfaces`CameraPermissionViewModel` and `QRCodeScanningViewModel`?

Also, would the interface for the setup of the buttons be implemented by `HomeActivity`?

2021-02-11 14:55 UTC, gnarula requested changes

2021-02-11 14:55 UTC, gnarula commented on app/src/main/java/com/github/dedis/student20_pop/home/HomeViewModel.java
> +    public void launchNewLao(String laoName) {
I think the argument can be removed and the name can be retrieved from `mLaoName`

2021-02-11 14:55 UTC, gnarula commented on app/src/main/java/com/github/dedis/student20_pop/home/HomeViewModel.java
> +    public void setLaoName(Editable name) {
```suggestion
    public void setLaoName(String name) {
```

Would make unit testing easier :)

2021-02-16 05:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dedis/student_21_pop?pullRequest=211) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/dedis/student_21_pop?pullRequest=211) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: celinecamacho<br/>:x: gnarula<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dedis/student_21_pop?pullRequest=211) it.</sub>

2021-02-19 11:24 UTC, gnarula approved these changes

2021-02-19 11:24 UTC, merged