Roll Call: Update protocol specification
dedis/student_21_pop pull request #287
Opened 2021-03-30 16:02 UTC by gnarula

Please refer to https://docs.google.com/document/d/1fyNWSPzLhM6W9V0VTFf2waMLiJGcscy7wa4bQlLkySM/edit#heading=h.snprjk777bwe

2021-04-05 10:13 UTC, flmichel requested changes
Looks good! I just have a minor comment.

2021-04-05 10:13 UTC, flmichel commented on protocol/query/method/message/data/dataCloseRollCall.json
>  	"required": ["object", "action", "update_id", "closes", "end", "attendees"],
I think "end" should be updated to "closed_at" here. Same thing for the updated fields in dataCreateRollCall.json and dataOpenRollCall.json.

2021-04-05 11:19 UTC, Kar1213 reviewed
Since now all roll calls that we close have been opened I think we could remove this part of the comment in "closes" field: "or in its absence, the 'id' field of the roll call creation"

2021-04-06 05:20 UTC, pierluca approved these changes
LGTM !

2021-04-06 08:17 UTC, flmichel approved these changes

2021-04-08 11:40 UTC, Kar1213 approved these changes

2021-04-11 12:07 UTC, merged

2021-04-13 18:54 UTC, pierluca commented
Following this change, the Fe1 tests are failing.
You might want to update them as needed @Adalsteinnjons @CaiMusso