HD Wallet implementation
dedis/student_21_pop pull request #373
Opened 2021-06-07 16:32 UTC by CaiMusso

Content proposed in this Pull Request
----------------------------
This branch adds the implementation of all **functions** needed by the **hierarchical deterministic Wallet**, as well as a new updated **Wallet UI:**
+ The user can create a new wallet or sync it's existing wallet. (already in master)
+ The wallet is initialised with a 12-word mnemonic which is translated to a **master key** (seed)
+ The wallet can now **generate a PoP token** (private and public key) starting from the personal seed and the **path** built using LAO and Roll Call Id.
+ The user can now **view all the PoP tokens associated with its seed** directly on the wallet page. Each of these tokens can be **copied** to clipboard using the copy button or **scanned** by pressing "show QR code".

### Remark
In order for the wallet to find all the PoP tokens associated with the current wallet it needs a **MAP**. This map should be of the form:

[LAO ID 1, ROLL CALL ID 1]     => [publicKey1, publicKey2, ... , publicKeyN]
[LAO ID 1, ROLL CALL ID 2]     => [publicKey1, publicKey2, ... , publicKeyN]
 .....
[LAO ID N, ROLL CALL ID N] => [publicKey1, publicKey2, ... , publicKeyN]

Namely, it should **map a duple (LAO ID, Roll Call ID) to a list of publicKeys which were scanned during the roll call**. This MAP has not yet been constructed in the typescript codebase (there is a TODO signalling this).

### Files that significantly changed
+ **HDWallet.ts -** the wallet **object**,  added all **hierarchical deterministic Wallet** functionalities (path derivation).
+ **WalletSyncedSeed -** the main **wallet UI**, added functionality to display all the tokens retrieved from the wallet.

### New files
+ **WalletError.tsx -** a page which informs the user that there was a synchronisation error with the wallet (e.g. mistyped the 12-word mnemonic seed).
+ **CopiableTextBlock.tsx -** a component (text block + button). You can copy the text in text block by pressing the copy icon
+ **CopyButton.tsx -** a component (button) with the copy icon

### Other changes worth mentioning
+ In **fe1-web/components/QRCode.tsx** a new props (**value**) was added. This way the QR code component is generic (namely gets the value it displays as a parameter). The codebase was modified (only in fe1-web/parts/lao/Identity.tsx) to match the new component.

New dependencies
-------------------------------------
+ [**ed25519-hd-key**](https://www.npmjs.com/package/ed25519-hd-key) - used to derive a private and public key for a given seed and a given path.

## TEST and Cross-Testing
The **Wallet.test.ts** covers all the procedure of token derivation from the beginning. It **creates** and **initialises** a wallet, then destroys it and re-**creates it from the Redux state**, verifies if it produces the same master key. 
Furthermore the seed, private key and public key are tested after being derived to be sure they produce the same result as the Java front-end when starting with the same 12-word mnemonic, LAO ID and RollCall ID. **The cross-testing is successful.**

Quick demo
-------------------------------
https://user-images.githubusercontent.com/47753346/121056517-91dfa980-c7be-11eb-8527-f1dfd562f99b.mov

2021-06-10 16:25 UTC, pierluca requested changes
A bunch of things in the various APIs of the classes (and some implementations) are a bit confusing.
I've tried to highlight them here.

2021-06-10 16:25 UTC, pierluca commented on fe1-web/__tests__/model/objects/Wallet.test.ts
> +      wallet.recoverAllKeys(testMap).then((laoAndRcIdsToTokenMap) => {
The API confuses me a bit here.

2021-06-13 11:53 UTC, CaiMusso commented on fe1-web/components/CopyButton.tsx
> +function CopyButton({ action }: IPropTypes) {
Yes very good point, thanks

2021-06-13 12:01 UTC, CaiMusso commented on fe1-web/components/CopiableTextBlock.tsx
> +      <CopyButton action={() => navigator.clipboard.writeText(text)} />
Sure right !

2021-08-10 22:27 UTC, merged