Add documentation in created objects
dedis/student_21_pop pull request #564
Opened 2021-11-04 14:25 UTC by jiabaow

2021-11-04 16:35 UTC, pierluca requested changes
Minor typo, otherwise LGTM

2021-11-04 16:35 UTC, pierluca commented on fe1-web/model/network/method/message/data/lao/CreateLao.ts
> +   * Creates a Lao object from a goven object
typo:
```suggestion
   * Creates a Lao object from a given object
```

2021-11-09 16:58 UTC, Xelowak approved these changes
Thanks for the addition ! I made some suggestions about typos. I think there should not be any changes to package.json if you just added documentation though.

2021-11-09 16:58 UTC, Xelowak commented on fe1-web/model/network/method/message/data/chirp/AddChirp.ts
> +   * Creates a AddChirp object from a given object
```suggestion
   * Creates an AddChirp object from a given object
```

2021-11-09 16:58 UTC, Xelowak commented on fe1-web/model/network/method/message/data/election/EndElection.ts
> +   * Creates a EndElection object from a given object
```suggestion
   * Creates an EndElection object from a given object
```

2021-11-09 16:58 UTC, Xelowak commented on fe1-web/model/network/method/message/data/election/SetupElection.ts
> +   * Creates a SetupSection object from a given object
```suggestion
   * Creates a SetupElection object from a given object
```

2021-11-09 16:58 UTC, Xelowak commented on fe1-web/model/network/method/message/data/lao/CreateLao.ts
> +/** Data sent to creat a Lao */
```suggestion
/** Data sent to create a Lao */
```

2021-11-09 16:58 UTC, Xelowak commented on fe1-web/model/network/method/message/data/lao/CreateLao.ts
> +   * Creates a Lao object from a given object
```suggestion
   * Creates a CreateLao object from a given object
```

2021-11-09 16:58 UTC, Xelowak commented on fe1-web/model/network/method/message/data/lao/UpdateLao.ts
> +/** data sent to update a Lao */
```suggestion
/** Data sent to update a Lao */
```

2021-11-09 16:58 UTC, Xelowak commented on fe1-web/model/network/method/message/data/lao/UpdateLao.ts
> +   * Creates a UpdateLao object from a given object
```suggestion
   * Creates an UpdateLao object from a given object
```

2021-11-09 16:58 UTC, Xelowak commented on fe1-web/model/network/method/message/data/meeting/CreateMeeting.ts
> +/** Data sent to creat a Meeting event */
```suggestion
/** Data sent to create a Meeting event */
```

2021-11-09 16:58 UTC, Xelowak commented on fe1-web/model/network/method/message/data/rollCall/CreateRollCall.ts
> +   * Creates a CreatRollCall object from a given object
```suggestion
   * Creates a CreateRollCall object from a given object
```

2021-11-09 16:58 UTC, Xelowak commented on fe1-web/model/network/method/message/data/rollCall/OpenRollCall.ts
> +   * Creates a OpenRollCall object from a given object
```suggestion
   * Creates an OpenRollCall object from a given object
```

2021-11-09 18:45 UTC, jiabaow commented
> Thanks for the addition ! I made some suggestions about typos. I think there should not be any changes to package.json if you just added documentation though.
Thanks for the suggestions! Some parts in package-lock have been updated after "npm i", I hope that's not a big problem.

2021-11-10 13:31 UTC, pierluca approved these changes
LGTM

2021-11-10 13:31 UTC, merged