Added chirp object and its tests
dedis/student_21_pop pull request #605
Opened 2021-11-19 15:05 UTC by Lugiasc

2021-11-21 18:31 UTC, arnauds5 submitted a review, later dismissed

2021-11-24 14:35 UTC, GabrielFleischer requested changes
Nitpicks

2021-11-24 14:35 UTC, GabrielFleischer commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/objects/Chirp.java
> +    this.id = id;
As you check that the id is not empty in the constructor, you might want to check it here too.

2021-11-24 14:35 UTC, GabrielFleischer commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/model/objects/ChirpTest.java
> +  private static final String id = "messageId";
```suggestion
  private static final String ID = "messageId";
```

2021-11-24 14:35 UTC, GabrielFleischer commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/model/objects/ChirpTest.java
> +  private static final Chirp chirp = new Chirp(id);
```suggestion
  private static final Chirp CHIRP = new Chirp(id);
```

2021-11-25 14:51 UTC, GabrielFleischer approved these changes

2021-11-28 16:57 UTC, arnauds5 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/objects/Chirp.java
> +      throw new IllegalArgumentException(" The id of the Chirp is empty");
There is an extra space in the string
```suggestion
      throw new IllegalArgumentException("The id is null");
    } else if (id.isEmpty()) {
      throw new IllegalArgumentException("The id of the Chirp is empty");
```

2021-11-28 16:57 UTC, arnauds5 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/objects/Chirp.java
> +      throw new IllegalArgumentException(" The id of the Chirp is empty");
There is an extra space in the string
```suggestion
      throw new IllegalArgumentException("The id is null");
    } else if (id.isEmpty()) {
      throw new IllegalArgumentException("The id of the Chirp is empty");
```

2021-11-28 16:57 UTC, arnauds5 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/objects/Chirp.java
> +  public void setTimestamp(Long timestamp) {
Using long instead of Long
```suggestion
  public void setTimestamp(long timestamp) {
```

2021-11-28 16:57 UTC, arnauds5 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/objects/Chirp.java
> +  public void setLikes(Integer likes) {
Using int instead of Integer
```suggestion
  public void setLikes(int likes) {
```

2021-11-29 11:15 UTC, arnauds5 approved these changes

2021-11-29 14:45 UTC, jbsv approved these changes

2021-11-29 18:37 UTC, merged