Go consensus phase 2
dedis/student_21_pop pull request #639
Opened 2021-12-05 14:55 UTC by Anghul

2021-12-05 19:37 UTC, arnauds5 requested changes

2021-12-05 19:37 UTC, arnauds5 commented on be1-go/channel/consensus/mod.go
> +	consensusInstance.accepts = append(consensusInstance.accepts, data)
Some checks are missing
```
on <ACCEPT, accepted_try, accepted_value> with accepted_try == proposed_try && accepted_value == proposed_value
    Accepts <-  Accepts ∪ {accepted_try, accepted_value} 
```

2021-12-05 19:37 UTC, arnauds5 commented on be1-go/channel/consensus/mod.go
> +			consensusInstance.decision = consensusInstance.proposed_value
consensusInstance.proposed_value is never modified and is still false at this point. (Learn always have decision=false here)

2021-12-07 00:04 UTC, celinecamacho reviewed
Looks great. Thank you for all the tests! I left a few comments about the consensus channel.

2021-12-07 21:07 UTC, rjaccard approved these changes
Nice pull request! Very well tested, that's cool :) 
I made a few (not very useful) comments.

2021-12-08 12:01 UTC, arnauds5 requested changes

2021-12-08 12:01 UTC, arnauds5 commented on be1-go/channel/consensus/mod.go
> +	err := msg.UnmarshalData(&msg)
This typo was causing the problem discussed on Slack.
```suggestion
	err := msg.UnmarshalData(&data)
```

2021-12-08 15:49 UTC, arnauds5 commented on be1-go/channel/consensus/mod.go
> +	}
Was this check added only for debuging ? If yes, it can be removed.

2021-12-08 17:28 UTC, arnauds5 submitted a review, later dismissed

2021-12-13 10:14 UTC, nkcr approved these changes

2021-12-13 10:26 UTC, merged