add check that the sender = organizer
dedis/student_21_pop pull request #650
Opened 2021-12-10 22:07 UTC by rjaccard

This solves issue #357

2021-12-14 14:20 UTC, Anghul requested changes
I don't think this fix work when there is multiple servers in the system, as only one server will know the organizer key

2021-12-15 15:02 UTC, rjaccard commented
> I don't think this fix work when there is multiple servers in the system, as only one server will know the organizer key

I'm not very familiar with the multiple servers scheme. Only the witnesses and organizers can have a server. So if I add a check for the type of the hub it would be enough, wouldn't be?

2021-12-16 07:56 UTC, nkcr commented on be1-go/channel/lao/mod.go
> +		return err
We always wrap errors ; )

2021-12-16 07:56 UTC, nkcr commented on be1-go/channel/lao/mod.go
> +		return err
error wrap

2021-12-16 07:56 UTC, nkcr commented on be1-go/channel/lao/mod.go
> +		return err
error wrap

2021-12-16 07:56 UTC, nkcr commented on be1-go/channel/lao/mod.go
> +func verifySenderIsOrganizer(msg message.Message, org kyber.Point) error {
this function could arguably be part of the Channel. Then you already have access to the organizerPukey and must only pass the message.

2021-12-16 07:56 UTC, nkcr commented on be1-go/channel/lao/mod.go
> +	return nil
I would add a newline above

2021-12-16 07:56 UTC, nkcr commented on be1-go/hub/standard_hub/mod.go
> +			publish.Params.Message.Sender)
```suggestion
		return answer.NewErrorf(-5, "sender's public key does not match the organizer's: %q != %q",
			senderPubKey, h.pubKeyOrg)
```

2021-12-16 10:07 UTC, Anghul commented
> > I don't think this fix work when there is multiple servers in the system, as only one server will know the organizer key
> 
> I'm not very familiar with the multiple servers scheme. Only the witnesses and organizers can have a server. So if I add a check for the type of the hub it would be enough, wouldn't be?

The biggest problem is that for createLAO, you are using the key known by the hub, but the hub know the key of its owner and not of the organizer. Therefore the witness won't be able to create the copy of the lao needed to keep the necessary state to communicate with the clients connecting to the lao using the witness (I don't know if I'm clear).
Adding a check to let the witness ignore this check isn't the best I think, because it would allow anyone to create a lao on the witnesses.
A possibility would be to make sure that the socket sending the message is an organizer socket, and trust that every message sent by the organizer is correct, but there is still a problem as for now the message are sent to all servers, then treated, so the organizer won't do the check before sending the message further.
I don't have more ideas of how that could be done.

2021-12-24 13:05 UTC, closed without merging